bind = 'unix:domotica.sock'
worker_class = 'sync'
workers = 1
loglevel = 'debug'
#accesslog = '/home/luca/Projects/Domotica/access_log.log'
acceslogformat ="%(h)s %(l)s %(u)s %(t)s %(r)s %(s)s %(b)s %(f)s %(a)s"
errorlog =  '/home/luca/Projects/Domotica/domotica_errors.log'